FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY target/clinic-0.1.0-SNAPSHOT.jar clinic.jar
EXPOSE 3000
ENTRYPOINT exec java $JAVA_OPTS -jar clinic.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar clinic.jar
